# 1. 스트림릿 패이지 생성 
* layout 설정 
* 

In [1]:
#Layout 

import streamlit as st

col1,col2 = st.columns([2,3])
# 공간을 2:3 으로 분할하여 col1과 col2라는 이름을 가진 컬럼을 생성합니다.  

with col1 :
  # column 1 에 담을 내용
  st.title('here is column1')
with col2 :
  # column 2 에 담을 내용
  st.title('here is column2')
  st.checkbox('this is checkbox1 in col2 ')


# with 구문 말고 다르게 사용 가능 
col1.subheader(' i am column1  subheader !! ')
col2.checkbox('this is checkbox2 in col2 ') 
#=>위에 with col2: 안의 내용과 같은 기능을합니다

2023-09-25 10:22:32.436 
  command:

    streamlit run /Users/sam/anaconda3/envs/WebScraping/lib/python3.10/site-packages/ipykernel_launcher.py [ARGUMENTS]


False

In [ ]:
# 이미지 불러오기 
import streamlit as st
from PIL import Image

#PIL 패키지에 이미지 모듈을 통해 이미지 열기 
# Image.open('이미지 경로')
zarathu_img = Image.open('zarathu.png')

col1,col2 = st.columns([2,3])

with col1 :
  # column 1 에 담을 내용
  st.title('here is column1')
with col2 :
  # column 2 에 담을 내용
  st.title('here is column2')
  st.checkbox('this is checkbox1 in col2 ')


# 컬럼2에 불러온 사진 표시하기
col2.image(zarathu_img)


In [ ]:
# 3.2 지도표시
import numpy as np
import pandas as pd 

#지도 위에 표시될 점 좌표 값을 위도경도에 담습니다 .
base_position =  [37.5073423, 127.0572734]
#중심점의 위도, 경도 좌표를 리스트에 담습니다.

# base_position에, 랜덤으로 생성한 값을 더하여 5개의 좌표를 데이터 프레임으로 생성하였고,
# 컬럼명은 위도 :lat  경도 lon으로 지정하였습니다. 

# map_data 에 정류소 x,y를 추축한 df 를 생성 저장 
map_data = pd.DataFrame( 
    np.random.randn(5, 1) / [20, 20] + base_position , 
    columns=['lat', 'lon'])
# map data 생성 : 위치와 경도 

print(map_data)

In [ ]:
st.code('st.map(map_data)')
# 웹사이트에 어떤 코드인지 표시해주기 
st.subheader('Map of Data ')
# 제목 생성 
st.map(map_data)
# 지도 생성 

In [11]:
import pandas as pd
import numpy as np

In [33]:
np_arr = np.array([37.10,127.20])  
np_row = np.array ([74.5073423, 254.0572734])

result = np.append(np_arr, np_row, axis=1)

print(result)

AxisError: axis 1 is out of bounds for array of dimension 1

In [29]:
arr = np.array([[1,2,3],[4,5,6]])
row = np.array([7,8,9])
arr = np.append(arr,[row],axis= 0)
print(arr)


coord_xy = np.array([[37.5073423, 127.0572734],[37.80, 127.05404] ] )

print(coord_xy)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 37.5073423 127.0572734]
 [ 37.8       127.05404  ]]


In [22]:
    df = pd.DataFrame(arr1, columns=['lat', 'lon'],)
    return df 

NameError: name 'arr1' is not defined

In [23]:
print(arr_to_df(coord_xy))

         lat         lon
0  37.507342  127.057273
1  37.800000  127.054040
